#!/usr/bin/env bun
// build-default.js <out.db>: builds a fresh studio/default.db from the repo's current STORYBOARD.md,
// studio/original-walkthrough.json and src/ch/*.js — the schema plus a single example version, "original", with the
// same title, logline, concept, status ('ready') and revision note as today's importOriginal (studio/versions.js).
// Its revision ids start at EXAMPLE_REVISION_FLOOR, not 1, so they never collide with user.db's. The database is
// created in rollback-journal mode (not WAL): read-only use (openDb's "def" attachment) then creates no -wal/-shm
// files next to it.
//
// Run as: bun studio/build-default.js studio/default.db
import { Database } from 'bun:sqlite';
import { readFileSync, readdirSync, existsSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SCHEMA, EXAMPLE_REVISION_FLOOR } from './db.js';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

export function buildDefault(root, outPath) {
  for (const f of [outPath, `${outPath}-wal`, `${outPath}-shm`, `${outPath}-journal`]) if (existsSync(f)) unlinkSync(f);

  const db = new Database(outPath, { create: true, strict: true });
  db.exec('PRAGMA journal_mode = DELETE;');
  db.exec(SCHEMA);

  const wt = JSON.parse(readFileSync(join(root, 'studio/original-walkthrough.json'), 'utf8'));
  const t = Date.now();
  db.query(`INSERT INTO versions (id, title, logline, concept, options, status, created_at, updated_at)
    VALUES ('original', $title, $logline, $concept, '{}', 'ready', $t, $t)`)
    .run({ title: wt.title, logline: wt.logline, concept: 'The original music video, generated by Claude Opus 5.5.', t });

  const files = [
    { path: 'STORYBOARD.md', content: readFileSync(join(root, 'STORYBOARD.md'), 'utf8') },
    { path: 'walkthrough.json', content: JSON.stringify(wt.chapters, null, 2) },
    ...readdirSync(join(root, 'src/ch')).filter(f => f.endsWith('.js')).sort()
      .map(f => ({ path: `ch/${f}`, content: readFileSync(join(root, 'src/ch', f), 'utf8') })),
  ];

  let rid = EXAMPLE_REVISION_FLOOR;
  for (const { path, content } of files) {
    db.query(`INSERT INTO revisions (id, version_id, path, content, job_id, source, note, created_at)
      VALUES ($id, 'original', $path, $content, NULL, 'import', 'imported from the repository', $t)`).run({ id: rid, path, content, t: Date.now() });
    db.query(`INSERT INTO files (version_id, path, content, revision_id) VALUES ('original', $path, $content, $rid)`).run({ path, content, rid });
    rid++;
  }

  db.close();
}

if (import.meta.main) {
  const out = process.argv[2];
  if (!out) { console.error('usage: bun studio/build-default.js <out.db>'); process.exit(1); }
  buildDefault(ROOT, out);
  console.log(`Built ${out}`);
}
